// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "todos", type: "link", link: { table: "todos" } },
      {
        name: "email",
        type: "email",
        notNull: true,
        defaultValue: "example@gmail.com",
      },
      {
        name: "password",
        type: "string",
        notNull: true,
        defaultValue: "123456",
      },
    ],
  },
  {
    name: "todos",
    columns: [
      { name: "user", type: "link", link: { table: "users" } },
      { name: "content", type: "string", notNull: true, defaultValue: "todo" },
      {
        name: "isComplete",
        type: "bool",
        notNull: true,
        defaultValue: "false",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Todos = InferredTypes["todos"];
export type TodosRecord = Todos & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
  todos: TodosRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://bradgarropy-s-workspace-8eg8mm.us-east-1.xata.sh/db/todos",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
